## Environment properties for Windows Test Execution
OS=Windows Server 2025
Hypervisor=Hyper-V
VM_Type=Windows_VM
SSD_Interface=NVMe
Test_Runner=Behave (Python BDD)
Report_Framework=Allure
IO_Tool=DiskSpd/FIO_on_WSL
HyperScale_Configuration=Dedicated_VMs_and_Shared_SSD_Scenarios